export const ABILITY_DESC: Record<string, string> = {
  "stench": "Helps repel wild POKéMON.",
  "drizzle": "Summons rain in battle.",
  "speed-boost": "Gradually boosts SPEED.",
  "battle-armor": "Blocks critical hits.",
  "sturdy": "Negates 1-hit KO attacks.",
  "damp": "Prevents self-destruction.",
  "limber": "Prevents paralysis.",
  "sand-veil": "Ups evasion in a sandstorm.",
  "static": "Paralyzes on contact.",
  "volt-absorb": "Turns electricity into HP.",
  "water-absorb": "Restores HP if hit by a Water-type move.",
  "oblivious": "Prevents attraction.",
  "cloud-nine": "Negates weather effects.",
  "compound-eyes": "Raises accuracy.",
  "insomnia": "Prevents sleep.",
  "color-change": "Changes type to foe’s move.",
  "immunity": "Prevents poisoning.",
  "flash-fire": "Powers up if hit by fire.",
  "shield-dust": "Prevents added effects.",
  "own-tempo": "Prevents confusion.",
  "suction-cups": "Firmly anchors the body.",
  "intimidate": "Lowers the foe’s ATTACK.",
  "shadow-tag": "Prevents the foe’s escape.",
  "rough-skin": "Hurts to touch.",
  "wonder-guard": "“Super effective” hits.",
  "levitate": "Gives full immunity to all Ground-type moves.",
  "effect-spore": "Leaves spores on contact.",
  "synchronize": "Passes on status problems.",
  "clear-body": "Prevents ability reduction.",
  "natural-cure": "Heals upon switching out.",
  "lightning-rod": "Draws electrical moves.",
  "serene-grace": "Promotes added effects.",
  "swift-swim": "Raises SPEED in rain.",
  "chlorophyll": "Raises SPEED in sunshine.",
  "illuminate": "Encounter rate increases.",
  "trace": "Copies special ability.",
  "huge-power": "Raises ATTACK.",
  "poison-point": "Poisons foe on contact.",
  "inner-focus": "Prevents flinching.",
  "magma-armor": "Prevents freezing.",
  "water-veil": "Prevents burns.",
  "magnet-pull": "Traps STEEL-type POKéMON.",
  "soundproof": "Avoids sound-based moves.",
  "rain-dish": "Slight HP recovery in rain.",
  "sand-stream": "Summons a sandstorm.",
  "pressure": "Raises foe’s PP usage.",
  "thick-fat": "Heat-and-cold protection.",
  "early-bird": "Awakens quickly from sleep.",
  "flame-body": "Burns the foe on contact.",
  "run-away": "Makes escaping easier.",
  "keen-eye": "Prevents loss of accuracy.",
  "hyper-cutter": "Prevents ATTACK reduction.",
  "pickup": "May pick up items.",
  "truant": "Moves only every two turns.",
  "hustle": "Trades accuracy for power.",
  "cute-charm": "Infatuates on contact.",
  "plus": "Powers up with MINUS.",
  "minus": "Powers up with PLUS.",
  "forecast": "Changes with the weather.",
  "sticky-hold": "Prevents item theft.",
  "shed-skin": "Heals the body by shedding.",
  "guts": "Ups ATTACK if suffering.",
  "marvel-scale": "Ups DEFENSE if suffering.",
  "liquid-ooze": "Draining causes injury.",
  "overgrow": "Powers up Grass-type moves in a pinch.",
  "blaze": "Ups FIRE moves in a pinch.",
  "torrent": "Ups WATER moves in a pinch.",
  "swarm": "Ups BUG moves in a pinch.",
  "rock-head": "Protects the Pokémon from recoil damage.",
  "drought": "Summons sunlight in battle.",
  "arena-trap": "Prevents fleeing.",
  "vital-spirit": "Prevents sleep.",
  "white-smoke": "Prevents ability reduction.",
  "pure-power": "Raises ATTACK.",
  "shell-armor": "Blocks critical hits.",
  "air-lock": "Negates weather effects.",
  "tangled-feet": "Raises evasion if the Pokémon is confused.",
  "motor-drive": "Raises Speed if hit by an Electric-type move.",
  "rivalry": "Raises Attack if the foe is of the same gender.",
  "steadfast": "Raises Speed each time the Pokémon flinches.",
  "snow-cloak": "Raises evasion in a hailstorm.",
  "gluttony": "Encourages the early use of a held Berry.",
  "anger-point": "Raises Attack upon taking a critical hit.",
  "unburden": "Raises Speed if a held item is used.",
  "heatproof": "Weakens the power of Fire-type moves.",
  "simple": "The Pokémon is prone to wild stat changes.",
  "dry-skin": "Reduces HP if it is hot. Water restores HP.",
  "download": "Adjusts power according to the foe’s ability.",
  "iron-fist": "Boosts the power of punching moves.",
  "poison-heal": "Restores HP if the Pokémon is poisoned.",
  "adaptability": "Powers up moves of the same type.",
  "skill-link": "Increases the frequency of multi-strike moves.",
  "hydration": "Heals status problems if it is raining.",
  "solar-power": "Boosts Sp. Atk, but lowers HP in sunshine.",
  "quick-feet": "Boosts Speed if there is a status problem.",
  "normalize": "All the Pokémon’s moves become the Normal type.",
  "sniper": "Powers up moves if they become critical hits.",
  "magic-guard": "The Pokémon only takes damage from attacks.",
  "no-guard": "Ensures the Pokémon and its foe’s attacks land.",
  "stall": "The Pokémon moves after even slower foes.",
  "technician": "Powers up the Pokémon’s weaker moves.",
  "leaf-guard": "Prevents status problems in sunny weather.",
  "klutz": "The Pokémon can’t use any held items.",
  "mold-breaker": "Moves can be used regardless of abilities.",
  "super-luck": "Heightens the critical-hit ratios of moves.",
  "aftermath": "Damages the foe landing the finishing hit.",
  "anticipation": "Senses the foe’s dangerous moves.",
  "forewarn": "Determines what moves the foe has.",
  "unaware": "Ignores any change in ability by the foe.",
  "tinted-lens": "Powers up “not very effective” moves.",
  "filter": "Powers down super­ effective moves.",
  "slow-start": "Temporarily halves Attack and Speed.",
  "scrappy": "Enables moves to hit Ghost-type foes.",
  "storm-drain": "The Pokémon draws in all Water-type moves.",
  "ice-body": "The Pokémon regains HP in a hailstorm.",
  "solid-rock": "Powers down super­ effective moves.",
  "snow-warning": "The Pokémon summons a hailstorm in battle.",
  "honey-gather": "The Pokémon may gather Honey from somewhere.",
  "frisk": "The Pokémon can check the foe’s held item.",
  "reckless": "Powers up moves that have recoil damage.",
  "multitype": "Changes type to match the held Plate.",
  "flower-gift": "Powers up party Pokémon when it is sunny.",
  "bad-dreams": "Reduces a sleeping foe’s HP.",
  "pickpocket": "Steals an item when hit by another Pokémon.",
  "sheer-force": "Removes added effects to increase move damage.",
  "contrary": "Makes stat changes have an opposite effect.",
  "unnerve": "Makes the foe nervous and unable to eat Berries.",
  "defiant": "When its stats are lowered its Attack increases.",
  "defeatist": "Lowers stats when HP becomes half or less.",
  "cursed-body": "May disable a move used on the Pokémon.",
  "healer": "May heal an ally’s status conditions.",
  "friend-guard": "Reduces damage done to allies.",
  "weak-armor": "Physical attacks lower Defense and raise Speed.",
  "heavy-metal": "Doubles the Pokémon’s weight.",
  "light-metal": "Halves the Pokémon’s weight.",
  "multiscale": "Reduces damage when HP is full.",
  "toxic-boost": "Powers up physical attacks when poisoned.",
  "flare-boost": "Powers up special attacks when burned.",
  "harvest": "May create another Berry after one is used.",
  "telepathy": "Anticipates an ally’s attack and dodges it.",
  "moody": "Raises one stat and lowers another.",
  "overcoat": "Protects the Pokémon from damage from weather.",
  "poison-touch": "May poison targets when a Pokémon makes contact.",
  "regenerator": "Restores a little HP when withdrawn from battle.",
  "big-pecks": "Protects the Pokémon from Defense-lowering attacks.",
  "sand-rush": "Boosts the Pokémon’s Speed in a sandstorm.",
  "wonder-skin": "Makes status-changing moves more likely to miss.",
  "analytic": "Boosts move power when the Pokémon moves last.",
  "illusion": "Comes out disguised as the Pokémon in back.",
  "imposter": "It transforms itself into the Pokémon it is facing.",
  "infiltrator": "Passes through the foe’s barrier and strikes.",
  "mummy": "Contact with this Pokémon spreads this Ability.",
  "moxie": "Boosts Attack after knocking out any Pokémon.",
  "justified": "Raises Attack when hit by a Dark-type move.",
  "rattled": "Some move types scare it and boost its Speed.",
  "magic-bounce": "Reflects status- changing moves.",
  "sap-sipper": "Boosts Attack when hit by a Grass-type move.",
  "prankster": "Gives priority to a status move.",
  "sand-force": "Boosts certain moves’ power in a sandstorm.",
  "iron-barbs": "Inflicts damage to the Pokémon on contact.",
  "zen-mode": "Changes the Pokémon’s shape when HP is halved.",
  "victory-star": "Boosts the accuracy of its allies and itself.",
  "turboblaze": "Moves can be used regardless of Abilities.",
  "teravolt": "Moves can be used regardless of Abilities.",
  "aroma-veil": "Protects allies from attacks that limit their move choices.",
  "flower-veil": "Prevents lowering of ally Grass-type Pokémon’s stats.",
  "cheek-pouch": "Restores HP as well when the Pokémon eats a Berry.",
  "protean": "Changes the Pokémon’s type to the type of the move it’s using.",
  "fur-coat": "Halves damage from physical moves.",
  "magician": "The Pokémon steals the held item of a Pokémon it hits with a move.",
  "bulletproof": "Protects the Pokémon from some ball and bomb moves.",
  "competitive": "Boosts the Sp. Atk stat when a stat is lowered.",
  "strong-jaw": "The Pokémon’s strong jaw gives it tremendous biting power.",
  "refrigerate": "Normal-type moves become Ice-type moves.",
  "sweet-veil": "Prevents itself and ally Pokémon from falling asleep.",
  "stance-change": "The Pokémon changes form depending on how it battles.",
  "gale-wings": "Gives priority to Flying-type moves.",
  "mega-launcher": "Powers up aura and pulse moves.",
  "grass-pelt": "Boosts the Defense stat in Grassy Terrain.",
  "symbiosis": "The Pokémon can pass an item to an ally.",
  "tough-claws": "Powers up moves that make direct contact.",
  "pixilate": "Normal-type moves become Fairy-type moves.",
  "gooey": "Contact with the Pokémon lowers the attacker’s Speed stat.",
  "aerilate": "Normal-type moves become Flying-type moves.",
  "parental-bond": "Parent and child attack together.",
  "dark-aura": "Powers up each Pokémon’s Dark-type moves.",
  "fairy-aura": "Powers up each Pokémon’s Fairy-type moves.",
  "aura-break": "The effects of “Aura” Abilities are reversed.",
  "primordial-sea": "Affects weather and nullifies any Fire-type attacks.",
  "desolate-land": "Affects weather and nullifies any Water-type attacks.",
  "delta-stream": "Affects weather and eliminates all of the Flying type’s weaknesses.",
  "stamina": "Boosts the Defense stat when hit by an attack.",
  "wimp-out": "The Pokémon cowardly switches out when its HP becomes half or less.",
  "emergency-exit": "The Pokémon, sensing danger, switches out when its HP becomes half or less.",
  "water-compaction": "Boosts the Pokémon’s Defense stat sharply when hit by a Water-type move.",
  "merciless": "The Pokémon’s attacks become critical hits if the target is poisoned.",
  "shields-down": "When its HP becomes half or less, the Pokémon’s shell breaks and it becomes aggressive.",
  "stakeout": "Doubles the damage dealt to the target’s replacement if the target switches out.",
  "water-bubble": "Lowers the power of Fire-type moves done to the Pokémon and prevents the Pokémon from getting a burn.",
  "steelworker": "Powers up Steel-type moves.",
  "berserk": "Boosts the Pokémon’s Sp. Atk stat when it takes a  hit that causes its HP to become half or less.",
  "slush-rush": "Boosts the Pokémon’s Speed stat in a hailstorm.",
  "long-reach": "The Pokémon uses its moves without making contact with the target.",
  "liquid-voice": "All sound-based moves become Water-type moves.",
  "triage": "Gives priority to a healing move.",
  "galvanize": "Normal-type moves become Electric-type moves. The power of those moves is boosted a little.",
  "surge-surfer": "Doubles the Pokémon’s Speed stat on Electric Terrain.",
  "schooling": "When it has a lot of HP, the Pokémon forms a powerful school. It stops schooling when its HP is low.",
  "disguise": "Once per battle, the shroud that covers the Pokémon can protect it from an attack.",
  "battle-bond": "Defeating an opposing Pokémon strengthens the Pokémon’s bond with its Trainer, and it becomes Ash-Greninja. Water Shuriken gets more powerful.",
  "power-construct": "Other Cells gather to aid when its HP becomes half or less. Then the Pokémon changes its form to Complete Forme.",
  "corrosion": "The Pokémon can poison the target even if it’s a Steel or Poison type.",
  "comatose": "It’s always drowsing and will never wake up. It can attack without waking up.",
  "queenly-majesty": "Its majesty pressures the opposing Pokémon, making it unable to attack using priority moves.",
  "innards-out": "Damages the attacker landing the finishing hit by the amount equal to its last HP.",
  "dancer": "When another Pokémon uses a dance move, it can use a dance move following it regardless of its Speed.",
  "battery": "Powers up ally Pokémon’s special moves.",
  "fluffy": "Halves the damage taken from moves that make direct contact, but doubles that of Fire-type moves.",
  "dazzling": "Surprises the opposing Pokémon, making it unable to attack using priority moves.",
  "soul-heart": "Boosts its Sp. Atk stat every time a Pokémon faints.",
  "tangling-hair": "Contact with the Pokémon lowers the attacker’s Speed stat.",
  "receiver": "The Pokémon copies the Ability of a defeated ally.",
  "power-of-alchemy": "The Pokémon copies the Ability of a defeated ally.",
  "beast-boost": "The Pokémon boosts its most proficient stat each time it knocks out a Pokémon.",
  "rks-system": "Changes the Pokémon’s type to match the memory disc it holds.",
  "electric-surge": "Turns the ground into Electric Terrain when the Pokémon enters a battle.",
  "psychic-surge": "Turns the ground into Psychic Terrain when the Pokémon enters a battle.",
  "misty-surge": "Turns the ground into Misty Terrain when the Pokémon enters a battle.",
  "grassy-surge": "Turns the ground into Grassy Terrain when the Pokémon enters a battle.",
  "full-metal-body": "Prevents other Pokémon’s moves or Abilities from lowering the Pokémon’s stats.",
  "shadow-shield": "Reduces the amount of damage the Pokémon takes while its HP is full.",
  "prism-armor": "Reduces the power of supereffective attacks taken.",
  "neuroforce": "Powers up moves that are super effective.",
  "intrepid-sword": "Boosts the Pokémon’s Attack stat when the Pokémon enters a battle.",
  "dauntless-shield": "Boosts the Pokémon’s Defense stat when the Pokémon enters a battle.",
  "libero": "Changes the Pokémon’s type to the type of the move it’s about to use.",
  "ball-fetch": "If the Pokémon is not holding an item, it will fetch the Poké Ball from the first failed throw of the battle.",
  "cotton-down": "When the Pokémon is hit by an attack, it scatters cotton fluff around and lowers the Speed stat of all Pokémon except itself.",
  "propeller-tail": "Ignores the effects of opposing Pokémon’s Abilities and moves that draw in moves.",
  "mirror-armor": "Bounces back only the stat-lowering effects that the Pokémon receives.",
  "gulp-missile": "When the Pokémon uses Surf or Dive, it will come back with prey. When it takes damage, it will spit out the prey to attack.",
  "stalwart": "Ignores the effects of opposing Pokémon’s Abilities and moves that draw in moves.",
  "steam-engine": "Boosts the Pokémon’s Speed stat drastically if hit by a Fire- or Water-type move.",
  "punk-rock": "Boosts the power of sound-based moves. The Pokémon also takes half the damage from these kinds of moves.",
  "sand-spit": "The Pokémon creates a sandstorm when it’s hit by an attack.",
  "ice-scales": "The Pokémon is protected by ice scales, which halve the damage taken from special moves.",
  "ripen": "Ripens Berries and doubles their effect.",
  "ice-face": "The Pokémon’s ice head can take a physical attack as a substitute, but the attack also changes the Pokémon’s appearance. The ice will be restored when it hails.",
  "power-spot": "Just being next to the Pokémon powers up moves.",
  "mimicry": "Changes the Pokémon’s type depending on the terrain.",
  "screen-cleaner": "When the Pokémon enters a battle, the effects of Light Screen, Reflect, and Aurora Veil are nullified for both opposing and ally Pokémon.",
  "steely-spirit": "Powers up ally Pokémon’s Steel-type moves.",
  "perish-body": "When hit by a move that makes direct contact, the Pokémon and the attacker will faint after three turns unless they switch out of battle.",
  "wandering-spirit": "The Pokémon exchanges Abilities with a Pokémon that hits it with a move that makes direct contact.",
  "gorilla-tactics": "Boosts the Pokémon’s Attack stat but only allows the use of the first selected move.",
  "neutralizing-gas": "If the Pokémon with Neutralizing Gas is in the battle, the effects of all Pokémon’s Abilities will be nullified or will not be triggered.",
  "pastel-veil": "Protects the Pokémon and its ally Pokémon from being poisoned.",
  "hunger-switch": "The Pokémon changes its form, alternating between its Full Belly Mode and Hangry Mode after the end of each turn.",
  "quick-draw": "Enables the Pokémon to move first occasionally.",
  "unseen-fist": "If the Pokémon uses moves that make direct contact, it can attack the target even if the target protects itself.",
  "curious-medicine": "When the Pokémon enters a battle, it scatters medicine from its shell, which removes all stat changes from allies.",
  "transistor": "Powers up Electric-type moves.",
  "dragons-maw": "Powers up Dragon-type moves.",
  "chilling-neigh": "When the Pokémon knocks out a target, it utters a chilling neigh, which boosts its Attack stat.",
  "grim-neigh": "When the Pokémon knocks out a target, it utters a terrifying neigh, which boosts its Sp. Atk stat.",
  "as-one-glastrier": "This Ability combines the effects of both Calyrex’s Unnerve Ability and Glastrier’s Chilling Neigh Ability.",
  "as-one-spectrier": "This Ability combines the effects of both Calyrex’s Unnerve Ability and Spectrier’s Grim Neigh Ability.",
  "lingering-aroma": "Contact with the Pokémon changes the attacker's Ability to Lingering Aroma.",
  "seed-sower": "Turns the ground into Grassy Terrain when the Pokémon is hit by an attack.",
  "thermal-exchange": "Boosts the Attack stat when the Pokémon is hit by a Fire-type move. The Pokémon also cannot be burned.",
  "anger-shell": "When an attack causes its HP to drop to half or less, the Pokémon gets angry. This lowers its Defense and Sp. Def stats but boosts its Attack, Sp. Atk, and Speed stats.",
  "purifying-salt": "The Pokémon's pure salt protects it from status conditions and halves the damage taken from Ghost-type moves.",
  "well-baked-body": "The Pokémon takes no damage when hit by Fire-type moves. Instead, its Defense stat is sharply boosted.",
  "wind-rider": "Boosts the Pokémon's Attack stat if Tailwind takes effect or if the Pokémon is hit by a wind move. The Pokémon also takes no damage from wind moves.",
  "guard-dog": "Boosts the Pokémon’s Attack stat if intimidated. Moves and items that would force the Pokémon to switch out also fail to work.",
  "rocky-payload": "Powers up Rock-type moves.",
  "wind-power": "The Pokémon becomes charged when it is hit by a wind move, boosting the power of the next Electric-type move the Pokémon uses.",
  "zero-to-hero": "The Pokémon transforms into its Hero Form when it switches out.",
  "commander": "When the Pokémon enters a battle, it goes inside the mouth of an ally Dondozo if one is on the field. The Pokémon then issues commands from there.",
  "electromorphosis": "The Pokémon becomes charged when it takes damage, boosting the power of the next Electric-type move the Pokémon uses.",
  "protosynthesis": "Boosts the Pokémon's most proficient stat in harsh sunlight or if the Pokémon is holding Booster Energy.",
  "quark-drive": "Boosts the Pokémon's most proficient stat on Electric Terrain or if the Pokémon is holding Booster Energy.",
  "good-as-gold": "A body of pure, solid gold gives the Pokémon full immunity to other Pokémon's status moves.",
  "vessel-of-ruin": "The power of the Pokémon's ruinous vessel lowers the Sp. Atk stats of all Pokémon except itself.",
  "sword-of-ruin": "The power of the Pokémon's ruinous sword lowers the Defense stats of all Pokémon except itself.",
  "tablets-of-ruin": "The power of the Pokémon's ruinous wooden tablets lowers the Attack stats of all Pokémon except itself.",
  "beads-of-ruin": "The power of the Pokémon's ruinous beads lowers the Sp. Def stats of all Pokémon except itself.",
  "orichalcum-pulse": "Turns the sunlight harsh when the Pokémon enters a battle. The ancient pulse thrumming through the Pokémon also boosts its Attack stat in harsh sunlight.",
  "hadron-engine": "Turns the ground into Electric Terrain when the Pokémon enters a battle. The futuristic engine within the Pokémon also boosts its Sp. Atk stat on Electric Terrain.",
  "opportunist": "If an opponent's stat is boosted, the Pokémon seizes the opportunity to boost the same stat for itself.",
  "cud-chew": "When the Pokémon eats a Berry, it will regurgitate that Berry at the end of the next turn and eat it one more time.",
  "sharpness": "Powers up slicing moves.",
  "supreme-overlord": "When the Pokémon enters a battle, its Attack and Sp. Atk stats are slightly boosted for each of the allies in its party that have already been defeated.",
  "costar": "When the Pokémon enters a battle, it copies an ally's stat changes.",
  "toxic-debris": "Scatters poison spikes at the feet of the opposing team when the Pokémon takes damage from physical moves.",
  "armor-tail": "The mysterious tail covering the Pokémon's head makes opponents unable to use priority moves against the Pokémon or its allies.",
  "earth-eater": "If hit by a Ground-type move, the Pokémon has its HP restored instead of taking damage.",
  "mycelium-might": "The Pokémon will always act more slowly when using status moves, but these moves will be unimpeded by the Ability of the target.",
  "minds-eye": "The Pokémon ignores changes to opponents' evasiveness, its accuracy can't be lowered, and it can hit Ghost types with Normal-type and Fighting-type moves",
  "supersweet-syrup": "Lowers the evasion of opposing Pokémon by 1 stage when first sent into battle",
  "hospitality": "When the Pokémon enters a battle, it showers its ally with hospitality, restoring a small amount of the ally's HP",
  "toxic-chain": "The power of the Pokémon's toxic chain may badly poison any target the Pokémon hits with a move",
  "embody-aspect": "The Pokémon's heart fills with memories, causing the Mask to shine and one of the Pokémon's stats to be boosted.",
  "tera-shift": "When the Pokémon enters a battle, it absorbs the energy around itself and transforms into its Terastal Form.",
  "tera-shell": "The Pokémon's shell contains the powers of each type. All damage-dealing moves that hit the Pokémon when its HP is full will not be very effective.",
  "teraform-zero": "When Terapagos changes into its Stellar Form, it uses its hidden powers to eliminate all effects of weather and terrain, reducing them to zero.",
  "poison-puppeteer": "Pokémon poisoned by Pecharunt's moves will also become confused."
};