import { BERRY_ITEMS } from './berryData';
export const ITEM_CATEGORIES = [
  { id: "all", label: "Tất cả" },
  { id: "stone-evolution", label: "Đá tiến hóa" },
  { id: "machine", label: "TMs & HMs" },
  { id: "standard-balls", label: "Poké Balls" },
  { id: "berry", label: "Quả mọng (Berries)" },
  { id: "healing", label: "Hồi phục & Cứu chữa" },
];

export const STATIC_ITEMS = [
  // Đá tiến hóa
  { id: 1, name: "fire-stone", label: "Fire Stone", category: "stone-evolution", cost: 3000, effect: "Tiến hóa Pokémon hệ Lửa." },
  { id: 2, name: "water-stone", label: "Water Stone", category: "stone-evolution", cost: 3000, effect: "Tiến hóa Pokémon hệ Nước." },
  { id: 3, name: "thunder-stone", label: "Thunder Stone", category: "stone-evolution", cost: 3000, effect: "Tiến hóa Pokémon hệ Điện." },
  { id: 4, name: "leaf-stone", label: "Leaf Stone", category: "stone-evolution", cost: 3000, effect: "Tiến hóa Pokémon hệ Cỏ." },
  { id: 5, name: "moon-stone", label: "Moon Stone", category: "stone-evolution", cost: 0, effect: "Tiến hóa Pokémon đặc biệt." },
  { id: 6, name: "sun-stone", label: "Sun Stone", category: "stone-evolution", cost: 0, effect: "Tiến hóa Pokémon đặc biệt." },
  { id: 7, name: "shiny-stone", label: "Shiny Stone", category: "stone-evolution", cost: 0, effect: "Tiến hóa Pokémon đặc biệt." },
  { id: 8, name: "dusk-stone", label: "Dusk Stone", category: "stone-evolution", cost: 0, effect: "Tiến hóa Pokémon đặc biệt." },
  { id: 9, name: "dawn-stone", label: "Dawn Stone", category: "stone-evolution", cost: 0, effect: "Tiến hóa Pokémon đặc biệt." },
  { id: 10, name: "ice-stone", label: "Ice Stone", category: "stone-evolution", cost: 0, effect: "Tiến hóa Pokémon hệ băng." },
  // Pokeballs
  { id: 11, name: "poke-ball", label: "Poké Ball", category: "standard-balls", cost: 200, effect: "Vật phẩm dùng để thu phục Pokémon hoang dã." },
  { id: 12, name: "great-ball", label: "Great Ball", category: "standard-balls", cost: 600, effect: "Loại bóng có tỷ lệ thu phục cao hơn Poké Ball." },
  { id: 13, name: "ultra-ball", label: "Ultra Ball", category: "standard-balls", cost: 1200, effect: "Loại bóng có tỷ lệ thu phục cực cao." },
  { id: 14, name: "master-ball", label: "Master Ball", category: "standard-balls", cost: 0, effect: "Thu phục bất kỳ Pokémon nào mà không bao giờ thất bại." },
  { id: 15, name: "quick-ball", label: "Quick Ball", category: "standard-balls", cost: 1000, effect: "Đạt hiệu quả cao nhất khi sử dụng ngay lúc bắt đầu trận đấu." },
  { id: 16, name: "safari-ball", label: "Safari Ball", category: "standard-balls", cost: 0, effect: "Chỉ bắt được trong vùng Safari Zones ở một số Gen nhất định" },
  { id: 17, name: "net-ball", label: "Net Ball", category: "standard-balls", cost: 1000, effect: "Đạt hiệu quả 3.5 lần so với Pokeball tiêu chuẩn khi bắt Pokemon hệ nước hay hệ bọ." },
  { id: 18, name: "dive-ball", label: "Dive Ball", category: "standard-balls", cost: 1000, effect: "Đạt hiệu quả 3.5 lần so với Pokeball tiêu chuẩn khi lướt, lặn hay câu cá." },
  { id: 19, name: "repeat-ball", label: "Repeat Ball", category: "standard-balls", cost: 1000, effect: "Đạt hiệu quả 3.5 lần so với Pokeball tiêu chuẩn khi bắt Pokemon đã bị thu phục." },
  { id: 20, name: "nest-ball", label: "Nest Ball", category: "standard-balls", cost: 1000, effect: "Loại bóng có tỷ lệ thu phục cao hơn nếu bắt Pokemon từ level 1 tới 29." },
  { id: 21, name: "timer-ball", label: "Timer Ball", category: "standard-balls", cost: 1000, effect: "Loại bóng có tỷ lệ thu phục cao hơn nếu bắt Pokemon từ lượt 4 và tối đa đạt 4x ở lượt 10." },
  { id: 22, name: "luxury-ball", label: "Luxury Ball", category: "standard-balls", cost: 3000, effect: "Loại bóng sẽ tăng gấp đôi tình bạn Pokemon được bắt." },
  { id: 23, name: "premier-ball", label: "Premier Ball", category: "standard-balls", cost: 0, effect: "Loại bóng tặng không bán." },
  { id: 24, name: "dusk-ball", label: "Dusk Ball", category: "standard-balls", cost: 1000, effect: "Đạt hiệu quả 3 lần so với Pokeball tiêu chuẩn nếu bắt Pokemon ở trong hang hoặc về đêm." },
  { id: 25, name: "heal-ball", label: "Heal Ball", category: "standard-balls", cost: 300, effect: "Loại bóng phục hồi hoàn toàn cho Pokemon." },
  { id: 26, name: "cherish-ball", label: "Cherish Ball", category: "standard-balls", cost: 0, effect: "Loại bóng tặng thông qua sự kiện không thể đạt được trong game." },
  { id: 27, name: "fast-ball", label: "Fast Ball", category: "standard-balls", cost: 1000, effect: "Đạt hiệu quả 4 lần so với Pokeball tiêu chuẩn nếu bắt Pokemon có speed cơ bản là 100." },
  { id: 28, name: "level-ball", label: "Level Ball", category: "standard-balls", cost: 0, effect: "Loại bóng tùy thuộc vào level người chơi so với Pokemon hoang dã mà có độ hiệu quả khác nhau." },
  { id: 29, name: "lure-ball", label: "Lure Ball", category: "standard-balls", cost: 0, effect: "Đạt hiệu quả 4 lần so với Pokeball tiêu chuẩn nếu bắt Pokemon khi đang câu." },
  { id: 30, name: "heavy-ball", label: "Heavy Ball", category: "standard-balls", cost: 0, effect: "Loại bóng thay đổi cân nặng Pokemon." },
  { id: 31, name: "love-ball", label: "Love Ball", category: "standard-balls", cost: 0, effect: "Đạt hiệu quả 8 lần so với Pokeball tiêu chuẩn nếu bắt Pokemon cùng giống loài nhưng khác giới." },
  { id: 32, name: "friend-ball", label: "Friend Ball", category: "standard-balls", cost: 0, effect: "Loại bóng set tình bạn pokemon là 150." },
  { id: 33, name: "moon-ball", label: "Moon Ball", category: "standard-balls", cost: 0, effect: "Đạt hiệu quả 4 lần so với Pokeball tiêu chuẩn nếu bắt Pokemon tiến hóa bằng Moon Stone." },
  { id: 34, name: "sport-ball", label: "Sport Ball", category: "standard-balls", cost: 0, effect: "Loại bóng event." },
  { id: 35, name: "dream-ball", label: "Dream Ball", category: "standard-balls", cost: 0, effect: "Đạt hiệu quả 4 lần so với Pokeball tiêu chuẩn nếu bắt Pokemon đang ngủ." },
  { id: 36, name: "beast-ball", label: "Beast Ball", category: "standard-balls", cost: 1000, effect: "Đạt hiệu quả 5 lần so với Pokeball tiêu chuẩn nếu bắt Pokemon Ultra Beast." },
  { id: 37, name: "park-ball", label: "Park Ball", category: "standard-balls", cost: 0, effect: "Loại bóng event." },
  // --- HỒI PHỤC & CỨU CHỮA (HEALING) ---
  { id: 38, name: "potion", label: "Potion", category: "healing", cost: 300, effect: "Hồi phục 20 HP cho Pokémon." },
  { id: 39, name: "super-potion", label: "Super Potion", category: "healing", cost: 700, effect: "Hồi phục 60 HP cho Pokémon." },
  { id: 40, name: "hyper-potion", label: "Hyper Potion", category: "healing", cost: 1200, effect: "Hồi phục 120 HP cho Pokémon." },
  { id: 41, name: "max-potion", label: "Max Potion", category: "healing", cost: 2500, effect: "Hồi phục hoàn toàn HP." },
  { id: 42, name: "full-restore", label: "Full Restore", category: "healing", cost: 3000, effect: "Hồi phục hoàn toàn HP và giải tất cả trạng thái xấu." },
  { id: 43, name: "revive", label: "Revive", category: "healing", cost: 1500, effect: "Hồi sinh Pokémon đã ngất xỉu và hồi 50% HP." },
  { id: 44, name: "max-revive", label: "Max Revive", category: "healing", cost: 0, effect: "Hồi sinh Pokémon đã ngất xỉu và hồi 100% HP." },
  { id: 45, name: "full-heal", label: "Full Heal", category: "healing", cost: 600, effect: "Giải quyết tất cả các vấn đề về trạng thái của Pokémon." },
  { id: 46, name: "ether", label: "Ether", category: "healing", cost: 0, effect: "Hồi phục 10 PP cho một move Pokemon." },
  { id: 47, name: "max-ether", label: "Max Ether", category: "healing", cost: 0, effect: "Hồi phục hoàn toàn PP cho một move Pokemon." },
  { id: 48, name: "elixir", label: "Elixir", category: "healing", cost: 0, effect: "Hồi phục 10 PP cho all move Pokemon." },
  { id: 49, name: "max-elixir", label: "Max Elixir", category: "healing", cost: 0, effect: "Hồi phục hoàn toàn PP cho all move Pokemon." },
  { id: 50, name: "antidote", label: "Antidote", category: "healing", cost: 200, effect: "Chữa trị độc cho một Pokemon." },
  { id: 51, name: "awakening", label: "Awakening", category: "healing", cost: 200, effect: "Chữa trị cho một Pokemon khỏi trạng thái ngủ." },
  { id: 52, name: "burn-heal", label: "Burn Heal", category: "healing", cost: 200, effect: "Chữa trị bỏng cho một Pokemon." },
  { id: 53, name: "ice-heal", label: "Ice Heal", category: "healing", cost: 200, effect: "Chữa trị đóng băng cho một Pokemon." },
  { id: 54, name: "paralyze-heal", label: "Paralyze Heal", category: "healing", cost: 200, effect: "Chữa trị tê liệt cho một Pokemon." },

  ...BERRY_ITEMS,
];

export const getItemSprite = (name: string) => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/${name}.png`;