export interface MachineItem {
  id: string;
  name: string;
  moveName: string;
  type: string;
  effect: string;
}

export const POKEMON_MACHINES_GEN9: MachineItem[] = [
  // PALDEA BASE GAME (TM001 - TM171)
  { id: "TM001", name: "TM001 - Take Down", moveName: "take-down", type: "normal", effect: "Húc mạnh vào đối phương, người dùng cũng bị phản sát thương nhẹ." },
  { id: "TM002", name: "TM002 - Charm", moveName: "charm", type: "fairy", effect: "Ánh nhìn đáng yêu làm đối thủ giảm mạnh chỉ số Attack." },
  { id: "TM003", name: "TM003 - Fake Tears", moveName: "fake-tears", type: "dark", effect: "Giả vờ khóc để giảm mạnh Sp. Def của đối thủ." },
  { id: "TM004", name: "TM004 - Agility", moveName: "agility", type: "psychic", effect: "Thư giãn cơ thể để tăng mạnh chỉ số Speed." },
  { id: "TM005", name: "TM005 - Mud-Slap", moveName: "mud-slap", type: "ground", effect: "Ném bùn vào mặt đối thủ để giảm độ chính xác của chúng." },
  { id: "TM006", name: "TM006 - Scary Face", moveName: "scary-face", type: "normal", effect: "Làm mặt đáng sợ để giảm mạnh Speed của đối thủ." },
  { id: "TM007", name: "TM007 - Protect", moveName: "protect", type: "normal", effect: "Bảo vệ bản thân khỏi mọi đòn tấn công trong lượt đó." },
  { id: "TM008", name: "TM008 - Fire Fang", moveName: "fire-fang", type: "fire", effect: "Cắn bằng răng lửa, có thể gây bỏng hoặc nao núng." },
  { id: "TM009", name: "TM009 - Thunder Fang", moveName: "thunder-fang", type: "electric", effect: "Cắn bằng răng điện, có thể gây tê liệt hoặc nao núng." },
  { id: "TM010", name: "TM010 - Ice Fang", moveName: "ice-fang", type: "ice", effect: "Cắn bằng răng băng, có thể gây đóng băng hoặc nao núng." },
  { id: "TM011", name: "TM011 - Water Pulse", moveName: "water-pulse", type: "water", effect: "Phóng sóng nước tấn công, có thể gây hỗn loạn." },
  { id: "TM012", name: "TM012 - Low Kick", moveName: "low-kick", type: "fighting", effect: "Đá vào chân đối thủ, đối thủ càng nặng sát thương càng cao." },
  { id: "TM013", name: "TM013 - Acid Spray", moveName: "acid-spray", type: "poison", effect: "Phun axit gây sát thương và giảm mạnh Sp. Def đối thủ." },
  { id: "TM014", name: "TM014 - Acrobatics", moveName: "acrobatics", type: "flying", effect: "Sát thương gấp đôi nếu người dùng không cầm vật phẩm." },
  { id: "TM015", name: "TM015 - Struggle Bug", moveName: "struggle-bug", type: "bug", effect: "Tấn công và làm giảm Sp. Atk của đối thủ." },
  { id: "TM016", name: "TM016 - Psybeam", moveName: "psybeam", type: "psychic", effect: "Phóng tia tâm linh, có khả năng gây hỗn loạn." },
  { id: "TM017", name: "TM017 - Confuse Ray", moveName: "confuse-ray", type: "ghost", effect: "Phóng tia sáng kỳ lạ khiến đối thủ bị hỗn loạn." },
  { id: "TM018", name: "TM018 - Thief", moveName: "thief", type: "dark", effect: "Tấn công và đánh cắp vật phẩm của đối phương." },
  { id: "TM019", name: "TM019 - Disarming Voice", moveName: "disarming-voice", type: "fairy", effect: "Tiếng hát mê hoặc gây sát thương không bao giờ hụt." },
  { id: "TM020", name: "TM020 - Trailblaze", moveName: "trailblaze", type: "grass", effect: "Tấn công và tăng chỉ số Speed cho bản thân." },
  { id: "TM021", name: "TM021 - Pounce", moveName: "pounce", type: "bug", effect: "Nhảy vào đối thủ và làm giảm Speed của chúng." },
  { id: "TM022", name: "TM022 - Chilling Water", moveName: "chilling-water", type: "water", effect: "Phun nước lạnh gây sát thương và giảm Attack đối thủ." },
  { id: "TM023", name: "TM023 - Charge Beam", moveName: "charge-beam", type: "electric", effect: "Tấn công bằng điện, có khả năng tăng Sp. Atk bản thân." },
  { id: "TM024", name: "TM024 - Fire Spin", moveName: "fire-spin", type: "fire", effect: "Nhốt đối thủ trong vòng xoáy lửa từ 4-5 lượt." },
  { id: "TM025", name: "TM025 - Facade", moveName: "facade", type: "normal", effect: "Sát thương gấp đôi nếu bị bỏng, tê liệt hoặc trúng độc." },
  { id: "TM026", name: "TM026 - Poison Tail", moveName: "poison-tail", type: "poison", effect: "Quất đuôi độc, dễ gây chí mạng và nhiễm độc." },
  { id: "TM027", name: "TM027 - Aerial Ace", moveName: "aerial-ace", type: "flying", effect: "Đòn đánh cực nhanh không bao giờ hụt mục tiêu." },
  { id: "TM028", name: "TM028 - Bulldoze", moveName: "bulldoze", type: "ground", effect: "Dẫm nát mặt đất và làm giảm Speed đối thủ." },
  { id: "TM029", name: "TM029 - Hex", moveName: "hex", type: "ghost", effect: "Sát thương gấp đôi nếu đối thủ đang bị trạng thái bất thường." },
  { id: "TM030", name: "TM030 - Snarl", moveName: "snarl", type: "dark", effect: "Gầm gừ gây sát thương và giảm Sp. Atk đối thủ." },
  { id: "TM031", name: "TM031 - Metal Claw", moveName: "metal-claw", type: "steel", effect: "Cào bằng móng vuốt thép, có thể tăng Attack bản thân." },
  { id: "TM032", name: "TM032 - Swift", moveName: "swift", type: "normal", effect: "Bắn ra các tia sáng hình sao không bao giờ hụt." },
  { id: "TM033", name: "TM033 - Magical Leaf", moveName: "magical-leaf", type: "grass", effect: "Phóng lá ma thuật không bao giờ hụt mục tiêu." },
  { id: "TM034", name: "TM034 - Icy Wind", moveName: "icy-wind", type: "ice", effect: "Thổi gió lạnh gây sát thương và giảm Speed đối thủ." },
  { id: "TM035", name: "TM035 - Mud Shot", moveName: "mud-shot", type: "ground", effect: "Bắn bùn gây sát thương và giảm Speed đối thủ." },
  { id: "TM036", name: "TM036 - Rock Tomb", moveName: "rock-tomb", type: "rock", effect: "Nhốt đối thủ trong đá và giảm Speed của chúng." },
  { id: "TM037", name: "TM037 - Draining Kiss", moveName: "draining-kiss", type: "fairy", effect: "Hôn đối thủ để hút HP hồi phục cho bản thân." },
  { id: "TM038", name: "TM038 - Flame Charge", moveName: "flame-charge", type: "fire", effect: "Húc lửa vào đối thủ và tăng Speed bản thân." },
  { id: "TM039", name: "TM039 - Low Sweep", moveName: "low-sweep", type: "fighting", effect: "Đá quét chân làm giảm Speed của đối thủ." },
  { id: "TM040", name: "TM040 - Air Cutter", moveName: "air-cutter", type: "flying", effect: "Dùng gió cắt đối thủ, tỉ lệ chí mạng cao." },
  { id: "TM041", name: "TM041 - Stored Power", moveName: "stored-power", type: "psychic", effect: "Sát thương tăng theo số lượng chỉ số được cộng thêm." },
  { id: "TM042", name: "TM042 - Night Shade", moveName: "night-shade", type: "ghost", effect: "Gây sát thương cố định bằng đúng Level của người dùng." },
  { id: "TM043", name: "TM043 - Fling", moveName: "fling", type: "dark", effect: "Ném vật phẩm đang cầm vào đối thủ để tấn công." },
  { id: "TM044", name: "TM044 - Dragon Tail", moveName: "dragon-tail", type: "dragon", effect: "Đuôi rồng đánh văng đối thủ, ép chúng phải đổi Pokémon." },
  { id: "TM045", name: "TM045 - Venoshock", moveName: "venoshock", type: "poison", effect: "Sát thương gấp đôi nếu đối thủ đang bị trúng độc." },
  { id: "TM046", name: "TM046 - Avalanche", moveName: "avalanche", type: "ice", effect: "Sát thương gấp đôi nếu người dùng bị đánh trúng trước trong lượt." },
  { id: "TM047", name: "TM047 - Endure", moveName: "endure", type: "normal", effect: "Chịu đựng để luôn còn ít nhất 1 HP trong lượt đó." },
  { id: "TM048", name: "TM048 - Volt Switch", moveName: "volt-switch", type: "electric", effect: "Tấn công rồi ngay lập tức rút về để đổi Pokémon khác." },
  { id: "TM049", name: "TM049 - Sunny Day", moveName: "sunny-day", type: "fire", effect: "Tạo ra thời tiết nắng gắt trong 5 lượt." },
  { id: "TM050", name: "TM050 - Rain Dance", moveName: "rain-dance", type: "water", effect: "Tạo ra thời tiết mưa lớn trong 5 lượt." },
  { id: "TM051", name: "TM051 - Sandstorm", moveName: "sandstorm", type: "rock", effect: "Tạo ra bão cát gây sát thương mỗi lượt trong 5 lượt." },
  { id: "TM052", name: "TM052 - Snowscape", moveName: "snowscape", type: "ice", effect: "Tạo ra thời tiết tuyết rơi tăng Defense cho hệ Băng." },
  { id: "TM053", name: "TM053 - Smart Strike", moveName: "smart-strike", type: "steel", effect: "Đâm bằng sừng thép không bao giờ hụt mục tiêu." },
  { id: "TM054", name: "TM054 - Psyshock", moveName: "psyshock", type: "psychic", effect: "Sát thương tâm linh tính theo chỉ số Defense vật lý của đối thủ." },
  { id: "TM055", name: "TM055 - Dig", moveName: "dig", type: "ground", effect: "Chui xuống đất ở lượt đầu và tấn công ở lượt thứ hai." },
  { id: "TM056", name: "TM056 - Bullet Seed", moveName: "bullet-seed", type: "grass", effect: "Bắn hạt 2-5 lần liên tiếp vào đối thủ." },
  { id: "TM057", name: "TM057 - False Swipe", moveName: "false-swipe", type: "normal", effect: "Đòn đánh luôn để lại cho đối thủ ít nhất 1 HP." },
  { id: "TM058", name: "TM058 - Brick Break", moveName: "brick-break", type: "fighting", effect: "Phá vỡ các rào chắn như Reflect hay Light Screen." },
  { id: "TM059", name: "TM059 - Zen Headbutt", moveName: "zen-headbutt", type: "psychic", effect: "Húc đầu bằng sức mạnh tâm linh, có thể gây nao núng." },
  { id: "TM060", name: "TM060 - U-turn", moveName: "u-turn", type: "bug", effect: "Tấn công rồi ngay lập tức rút về để đổi Pokémon khác." },
  { id: "TM061", name: "TM061 - Shadow Claw", moveName: "shadow-claw", type: "ghost", effect: "Cào bằng móng vuốt bóng tối, tỉ lệ chí mạng cao." },
  { id: "TM062", name: "TM062 - Foul Play", moveName: "foul-play", type: "dark", effect: "Dùng chính chỉ số Attack của đối thủ để gây sát thương." },
  { id: "TM063", name: "TM063 - Psychic Fangs", moveName: "psychic-fangs", type: "psychic", effect: "Cắn bằng răng tâm linh và phá vỡ các loại rào chắn." },
  { id: "TM064", name: "TM064 - Bulk Up", moveName: "bulk-up", type: "fighting", effect: "Gồng cơ bắp để tăng cả Attack và Defense." },
  { id: "TM065", name: "TM065 - Air Slash", moveName: "air-slash", type: "flying", effect: "Cắt không khí gây sát thương, có thể khiến đối thủ nao núng." },
  { id: "TM066", name: "TM066 - Body Slam", moveName: "body-slam", type: "normal", effect: "Dùng cả cơ thể đè bẹp đối thủ, có cơ hội gây tê liệt." },
  { id: "TM067", name: "TM067 - Fire Punch", moveName: "fire-punch", type: "fire", effect: "Đấm lửa vào đối thủ, có cơ hội gây bỏng." },
  { id: "TM068", name: "TM068 - Thunder Punch", moveName: "thunder-punch", type: "electric", effect: "Đấm điện vào đối thủ, có cơ hội gây tê liệt." },
  { id: "TM069", name: "TM069 - Ice Punch", moveName: "ice-punch", type: "ice", effect: "Đấm băng vào đối thủ, có cơ hội gây đóng băng." },
  { id: "TM070", name: "TM070 - Sleep Talk", moveName: "sleep-talk", type: "normal", effect: "Sử dụng ngẫu nhiên một chiêu thức khác khi đang ngủ." },
  { id: "TM071", name: "TM071 - Seed Bomb", moveName: "seed-bomb", type: "grass", effect: "Bắn một hạt giống lớn nổ tung vào đối thủ." },
  { id: "TM072", name: "TM072 - Electro Ball", moveName: "electro-ball", type: "electric", effect: "Càng nhanh hơn đối thủ thì sát thương gây ra càng lớn." },
  { id: "TM073", name: "TM073 - Drain Punch", moveName: "drain-punch", type: "fighting", effect: "Đấm và hút HP của đối thủ để hồi phục bản thân." },
  { id: "TM074", name: "TM074 - Reflect", moveName: "reflect", type: "psychic", effect: "Tạo rào chắn giảm sát thương vật lý nhận vào trong 5 lượt." },
  { id: "TM075", name: "TM075 - Light Screen", moveName: "light-screen", type: "psychic", effect: "Tạo rào chắn giảm sát thương đặc biệt nhận vào trong 5 lượt." },
  { id: "TM076", name: "TM076 - Rock Blast", moveName: "rock-blast", type: "rock", effect: "Chọi đá 2-5 lần liên tiếp vào mục tiêu." },
  { id: "TM077", name: "TM077 - Waterfall", moveName: "waterfall", type: "water", effect: "Lao tới như thác đổ, có thể khiến đối thủ nao núng." },
  { id: "TM078", name: "TM078 - Dragon Claw", moveName: "dragon-claw", type: "dragon", effect: "Cào đối phương bằng móng vuốt rồng sắc nhọn." },
  { id: "TM079", name: "TM079 - Dazzling Gleam", moveName: "dazzling-gleam", type: "fairy", effect: "Phát ra luồng sáng chói lòa tấn công mọi đối thủ." },
  { id: "TM080", name: "TM080 - Metronome", moveName: "metronome", type: "normal", effect: "Vẩy tay để sử dụng ngẫu nhiên gần như bất kỳ chiêu thức nào." },
  { id: "TM081", name: "TM081 - Grass Knot", moveName: "grass-knot", type: "grass", effect: "Dùng cỏ ngáng chân, đối thủ càng nặng sát thương càng lớn." },
  { id: "TM082", name: "TM082 - Thunder Wave", moveName: "thunder-wave", type: "electric", effect: "Phóng tia điện yếu khiến đối thủ bị tê liệt." },
  { id: "TM083", name: "TM083 - Poison Jab", moveName: "poison-jab", type: "poison", effect: "Đâm bằng tay độc, có khả năng cao gây nhiễm độc." },
  { id: "TM084", name: "TM084 - Stomping Tantrum", moveName: "stomping-tantrum", type: "ground", effect: "Sát thương gấp đôi nếu chiêu trước đó bị trượt hoặc thất bại." },
  { id: "TM085", name: "TM085 - Rest", moveName: "rest", type: "psychic", effect: "Ngủ trong 2 lượt để hồi phục toàn bộ HP và trạng thái." },
  { id: "TM086", name: "TM086 - Rock Slide", moveName: "rock-slide", type: "rock", effect: "Dội đá vào đối thủ, có cơ hội gây nao núng." },
  { id: "TM087", name: "TM087 - Taunt", moveName: "taunt", type: "dark", effect: "Châm chọc khiến đối thủ chỉ có thể dùng đòn tấn công." },
  { id: "TM088", name: "TM088 - Swords Dance", moveName: "swords-dance", type: "normal", effect: "Điệu nhảy kiếm giúp tăng mạnh chỉ số Attack." },
  { id: "TM089", name: "TM089 - Body Press", moveName: "body-press", type: "fighting", effect: "Dùng Defense thay cho Attack để tính sát thương." },
  { id: "TM090", name: "TM090 - Spikes", moveName: "spikes", type: "ground", effect: "Rải chông gây sát thương khi đối thủ đổi Pokémon vào sân." },
  { id: "TM091", name: "TM091 - Toxic Spikes", moveName: "toxic-spikes", type: "poison", effect: "Rải chông độc khiến đối thủ bị nhiễm độc khi vào sân." },
  { id: "TM092", name: "TM092 - Imprison", moveName: "imprison", type: "psychic", effect: "Ngăn đối thủ dùng các chiêu thức giống với người dùng." },
  { id: "TM093", name: "TM093 - Flash Cannon", moveName: "flash-cannon", type: "steel", effect: "Gom năng lượng thép rồi phóng ra, có thể giảm Sp. Def đối thủ." },
  { id: "TM094", name: "TM094 - Dark Pulse", moveName: "dark-pulse", type: "dark", effect: "Phóng luồng hắc ám gây sát thương và có thể gây nao núng." },
  { id: "TM095", name: "TM095 - Leech Life", moveName: "leech-life", type: "bug", effect: "Hút máu đối thủ cực mạnh để hồi phục HP." },
  { id: "TM096", name: "TM096 - Eerie Impulse", moveName: "eerie-impulse", type: "electric", effect: "Phát ra xung điện làm giảm mạnh Sp. Atk của đối thủ." },
  { id: "TM097", name: "TM097 - Fly", moveName: "fly", type: "flying", effect: "Bay lên cao ở lượt đầu và lao xuống tấn công ở lượt sau." },
  { id: "TM098", name: "TM098 - Skill Swap", moveName: "skill-swap", type: "psychic", effect: "Trao đổi đặc tính (Ability) giữa người dùng và đối thủ." },
  { id: "TM099", name: "TM099 - Iron Head", moveName: "iron-head", type: "steel", effect: "Húc đầu cứng như thép, có thể khiến đối thủ nao núng." },
  { id: "TM100", name: "TM100 - Dragon Dance", moveName: "dragon-dance", type: "dragon", effect: "Điệu nhảy rồng giúp tăng chỉ số Attack và Speed." },
  { id: "TM101", name: "TM101 - Power Gem", moveName: "power-gem", type: "rock", effect: "Tấn công bằng tia sáng lấp lánh như đá quý." },
  { id: "TM102", name: "TM102 - Gunk Shot", moveName: "gunk-shot", type: "poison", effect: "Bắn rác thải độc hại, có khả năng cao gây nhiễm độc." },
  { id: "TM103", name: "TM103 - Substitute", moveName: "substitute", type: "normal", effect: "Hy sinh 1/4 HP để tạo ra một hình nhân thế mạng." },
  { id: "TM104", name: "TM104 - Iron Defense", moveName: "iron-defense", type: "steel", effect: "Làm cứng cơ thể như sắt để tăng mạnh Defense." },
  { id: "TM105", name: "TM105 - X-Scissor", moveName: "x-scissor", type: "bug", effect: "Chém đối thủ bằng đôi càng chéo nhau." },
  { id: "TM106", name: "TM106 - Drill Run", moveName: "drill-run", type: "ground", effect: "Xoay người như mũi khoan, tỉ lệ chí mạng cao." },
  { id: "TM107", name: "TM107 - Will-O-Wisp", moveName: "will-o-wisp", type: "fire", effect: "Bắn ra ngọn lửa ma trơi khiến đối thủ bị bỏng." },
  { id: "TM108", name: "TM108 - Crunch", moveName: "crunch", type: "dark", effect: "Cắn mạnh bằng răng sắc nhọn, có thể giảm Defense đối thủ." },
  { id: "TM109", name: "TM109 - Trick", moveName: "trick", type: "psychic", effect: "Đánh tráo vật phẩm đang cầm với đối thủ." },
  { id: "TM110", name: "TM110 - Liquidation", moveName: "liquidation", type: "water", effect: "Dùng dòng nước mạnh tấn công, có thể giảm Defense đối thủ." },
  { id: "TM111", name: "TM111 - Giga Drain", moveName: "giga-drain", type: "grass", effect: "Hút sinh lực đối thủ để hồi phục một nửa HP sát thương gây ra." },
  { id: "TM112", name: "TM112 - Aura Sphere", moveName: "aura-sphere", type: "fighting", effect: "Phóng quả cầu năng lượng không bao giờ hụt mục tiêu." },
  { id: "TM113", name: "TM113 - Tailwind", moveName: "tailwind", type: "flying", effect: "Tạo luồng gió thuận chiều tăng gấp đôi Speed phe mình trong 4 lượt." },
  { id: "TM114", name: "TM114 - Shadow Ball", moveName: "shadow-ball", type: "ghost", effect: "Ném quả cầu bóng tối, có thể giảm Sp. Def đối thủ." },
  { id: "TM115", name: "TM115 - Dragon Pulse", moveName: "dragon-pulse", type: "dragon", effect: "Tấn công bằng luồng sóng xung kích từ miệng rồng." },
  { id: "TM116", name: "TM116 - Stealth Rock", moveName: "stealth-rock", type: "rock", effect: "Rải đá gây sát thương khi đối thủ đổi Pokémon vào sân." },
  { id: "TM117", name: "TM117 - Hyper Voice", moveName: "hyper-voice", type: "normal", effect: "Hét cực lớn gây sát thương bằng sóng âm." },
  { id: "TM118", name: "TM118 - Heat Wave", moveName: "heat-wave", type: "fire", effect: "Thổi luồng khí nóng bỏng, có thể gây bỏng đối thủ." },
  { id: "TM119", name: "TM119 - Energy Ball", moveName: "energy-ball", type: "grass", effect: "Bắn quả cầu năng lượng thiên nhiên, có thể giảm Sp. Def đối thủ." },
  { id: "TM120", name: "TM120 - Psychic", moveName: "psychic", type: "psychic", effect: "Tấn công tâm linh mạnh mẽ, có thể giảm Sp. Def đối thủ." },
  { id: "TM121", name: "TM121 - Heavy Slam", moveName: "heavy-slam", type: "steel", effect: "Đè bẹp đối thủ, người dùng càng nặng hơn mục tiêu sát thương càng cao." },
  { id: "TM122", name: "TM122 - Encore", moveName: "encore", type: "normal", effect: "Bắt đối thủ lặp lại chiêu thức vừa dùng trong 3 lượt." },
  { id: "TM123", name: "TM123 - Surf", moveName: "surf", type: "water", effect: "Tạo sóng thần tấn công mọi Pokémon xung quanh trên sân." },
  { id: "TM124", name: "TM124 - Ice Spinner", moveName: "ice-spinner", type: "ice", effect: "Xoay người đóng băng mặt sân và phá hủy mọi loại địa hình (Terrain)." },
  { id: "TM125", name: "TM125 - Flamethrower", moveName: "flamethrower", type: "fire", effect: "Phun lửa thiêu đốt đối thủ, có cơ hội gây bỏng." },
  { id: "TM126", name: "TM126 - Thunderbolt", moveName: "thunderbolt", type: "electric", effect: "Phóng tia điện mạnh mẽ, có cơ hội gây tê liệt." },
  { id: "TM127", name: "TM127 - Play Rough", moveName: "play-rough", type: "fairy", effect: "Đùa giỡn thô bạo với đối thủ, có thể giảm Attack của chúng." },
  { id: "TM128", name: "TM128 - Amnesia", moveName: "amnesia", type: "psychic", effect: "Tạm thời quên đi mọi thứ để tăng mạnh Sp. Def." },
  { id: "TM129", name: "TM129 - Calm Mind", moveName: "calm-mind", type: "psychic", effect: "Tập trung tâm trí để tăng cả Sp. Atk và Sp. Def." },
  { id: "TM130", name: "TM130 - Helping Hand", moveName: "helping-hand", type: "normal", effect: "Hỗ trợ đồng đội tăng mạnh sát thương đòn đánh trong lượt đó." },
  { id: "TM131", name: "TM131 - Pollen Puff", moveName: "pollen-puff", type: "bug", effect: "Gây sát thương nếu đánh đối thủ, hồi HP nếu đánh đồng đội." },
  { id: "TM132", name: "TM132 - Baton Pass", moveName: "baton-pass", type: "normal", effect: "Đổi Pokémon khác và chuyển lại mọi chỉ số đang được tăng/giảm." },
  { id: "TM133", name: "TM133 - Earth Power", moveName: "earth-power", type: "ground", effect: "Giải phóng sức mạnh mặt đất, có thể giảm Sp. Def đối thủ." },
  { id: "TM134", name: "TM134 - Reversal", moveName: "reversal", type: "fighting", effect: "HP người dùng càng thấp thì sát thương gây ra càng lớn." },
  { id: "TM135", name: "TM135 - Ice Beam", moveName: "ice-beam", type: "ice", effect: "Phóng tia băng giá cực mạnh, có cơ hội gây đóng băng." },
  { id: "TM136", name: "TM136 - Electric Terrain", moveName: "electric-terrain", type: "electric", effect: "Tạo địa hình điện trong 5 lượt, ngăn Pokémon bị ngủ." },
  { id: "TM137", name: "TM137 - Grassy Terrain", moveName: "grassy-terrain", type: "grass", effect: "Tạo địa hình cỏ trong 5 lượt, hồi HP mỗi lượt." },
  { id: "TM138", name: "TM138 - Psychic Terrain", moveName: "psychic-terrain", type: "psychic", effect: "Tạo địa hình tâm linh, ngăn các đòn ưu tiên (priority)." },
  { id: "TM139", name: "TM139 - Misty Terrain", moveName: "misty-terrain", type: "fairy", effect: "Tạo địa hình sương mù, ngăn các trạng thái bất thường." },
  { id: "TM140", name: "TM140 - Nasty Plot", moveName: "nasty-plot", type: "dark", effect: "Suy nghĩ xấu xa giúp tăng mạnh chỉ số Sp. Atk." },
  { id: "TM141", name: "TM141 - Fire Blast", moveName: "fire-blast", type: "fire", effect: "Phóng luồng lửa hình chữ Đại, có cơ hội gây bỏng cao." },
  { id: "TM142", name: "TM142 - Hydro Pump", moveName: "hydro-pump", type: "water", effect: "Bắn vòi rồng nước áp lực cao cực mạnh." },
  { id: "TM143", name: "TM143 - Blizzard", moveName: "blizzard", type: "ice", effect: "Tạo bão tuyết dữ dội tấn công, có cơ hội gây đóng băng." },
  { id: "TM144", name: "TM144 - Fire Pledge", moveName: "fire-pledge", type: "fire", effect: "Đòn đánh phối hợp hệ Lửa, mạnh hơn khi dùng cùng hệ Cỏ/Nước." },
  { id: "TM145", name: "TM145 - Water Pledge", moveName: "water-pledge", type: "water", effect: "Đòn đánh phối hợp hệ Nước, mạnh hơn khi dùng cùng hệ Lửa/Cỏ." },
  { id: "TM146", name: "TM146 - Grass Pledge", moveName: "grass-pledge", type: "grass", effect: "Đòn đánh phối hợp hệ Cỏ, mạnh hơn khi dùng cùng hệ Nước/Lửa." },
  { id: "TM147", name: "TM147 - Wild Charge", moveName: "wild-charge", type: "electric", effect: "Húc điện điên cuồng, người dùng cũng bị phản sát thương." },
  { id: "TM148", name: "TM148 - Sludge Bomb", moveName: "sludge-bomb", type: "poison", effect: "Ném bom bùn độc, có khả năng cao gây nhiễm độc." },
  { id: "TM149", name: "TM149 - Earthquake", moveName: "earthquake", type: "ground", effect: "Gây động đất mạnh tấn công tất cả Pokémon trên sân." },
  { id: "TM150", name: "TM150 - Stone Edge", moveName: "stone-edge", type: "rock", effect: "Đâm đối phương bằng đá nhọn, tỉ lệ chí mạng cao." },
  { id: "TM151", name: "TM151 - Phantom Force", moveName: "phantom-force", type: "ghost", effect: "Biến mất ở lượt đầu và tấn công xuyên bảo vệ ở lượt sau." },
  { id: "TM152", name: "TM152 - Giga Impact", moveName: "giga-impact", type: "normal", effect: "Đòn tấn công vật lý cực mạnh nhưng cần nghỉ 1 lượt sau đó." },
  { id: "TM153", name: "TM153 - Blast Burn", moveName: "blast-burn", type: "fire", effect: "Đòn hệ Lửa mạnh nhất cho starter, cần nghỉ 1 lượt." },
  { id: "TM154", name: "TM154 - Hydro Cannon", moveName: "hydro-cannon", type: "water", effect: "Đòn hệ Nước mạnh nhất cho starter, cần nghỉ 1 lượt." },
  { id: "TM155", name: "TM155 - Frenzy Plant", moveName: "frenzy-plant", type: "grass", effect: "Đòn hệ Cỏ mạnh nhất cho starter, cần nghỉ 1 lượt." },
  { id: "TM156", name: "TM156 - Outrage", moveName: "outrage", type: "dragon", effect: "Tấn công điên cuồng trong 2-3 lượt rồi bị hỗn loạn." },
  { id: "TM157", name: "TM157 - Overheat", moveName: "overheat", type: "fire", effect: "Nhiệt độ cực cao gây sát thương lớn nhưng giảm mạnh Sp. Atk." },
  { id: "TM158", name: "TM158 - Focus Blast", moveName: "focus-blast", type: "fighting", effect: "Gom tụ năng lượng rồi phóng ra, có thể giảm Sp. Def đối thủ." },
  { id: "TM159", name: "TM159 - Leaf Storm", moveName: "leaf-storm", type: "grass", effect: "Bão lá cực mạnh nhưng giảm mạnh Sp. Atk của người dùng." },
  { id: "TM160", name: "TM160 - Hurricane", moveName: "hurricane", type: "flying", effect: "Tạo cuồng phong tấn công, có cơ hội gây hỗn loạn." },
  { id: "TM161", name: "TM161 - Trick Room", moveName: "trick-room", type: "psychic", effect: "Tạo không gian dị biệt khiến Pokémon chậm hơn đánh trước." },
  { id: "TM162", name: "TM162 - Bug Buzz", moveName: "bug-buzz", type: "bug", effect: "Phát ra sóng âm rung động cực mạnh, có thể giảm Sp. Def đối thủ." },
  { id: "TM163", name: "TM163 - Hyper Beam", moveName: "hyper-beam", type: "normal", effect: "Tia năng lượng cường độ cao, cần nghỉ 1 lượt sau khi dùng." },
  { id: "TM164", name: "TM164 - Brave Bird", moveName: "brave-bird", type: "flying", effect: "Lao vào đối thủ dũng mãnh nhưng bị phản sát thương lớn." },
  { id: "TM165", name: "TM165 - Flare Blitz", moveName: "flare-blitz", type: "fire", effect: "Húc lửa cực mạnh nhưng người dùng bị phản sát thương." },
  { id: "TM166", name: "TM166 - Thunder", moveName: "thunder", type: "electric", effect: "Sét đánh cực mạnh, có cơ hội gây tê liệt cao." },
  { id: "TM167", name: "TM167 - Close Combat", moveName: "close-combat", type: "fighting", effect: "Áp sát tấn công liên tiếp nhưng giảm Defense và Sp. Def." },
  { id: "TM168", name: "TM168 - Solar Beam", moveName: "solar-beam", type: "grass", effect: "Tích tụ ánh sáng ở lượt đầu và bắn ở lượt sau." },
  { id: "TM169", name: "TM169 - Draco Meteor", moveName: "draco-meteor", type: "dragon", effect: "Triệu hồi thiên thạch rồng nhưng giảm mạnh Sp. Atk người dùng." },
  { id: "TM170", name: "TM170 - Steel Beam", moveName: "steel-beam", type: "steel", effect: "Bắn tia thép cực mạnh nhưng tiêu tốn 1/2 HP tối đa." },
  { id: "TM171", name: "TM171 - Tera Blast", moveName: "tera-blast", type: "normal", effect: "Đòn đánh đổi hệ theo hệ Terastal của Pokémon." },

  // DLC 1: THE TEAL MASK (TM172 - TM201)
  { id: "TM172", name: "TM172 - Roar", moveName: "roar", type: "normal", effect: "Tiếng gầm xua đuổi đối thủ và ép chúng đổi Pokémon." },
  { id: "TM173", name: "TM173 - Charge", moveName: "charge", type: "electric", effect: "Tích điện để tăng Sp. Def và gấp đôi sát thương đòn điện sau." },
  { id: "TM174", name: "TM174 - Haze", moveName: "haze", type: "ice", effect: "Tạo màn sương xóa bỏ mọi thay đổi chỉ số của tất cả Pokémon." },
  { id: "TM175", name: "TM175 - Toxic", moveName: "toxic", type: "poison", effect: "Gây độc nặng, sát thương tăng dần theo thời gian." },
  { id: "TM176", name: "TM176 - Sand Tomb", moveName: "sand-tomb", type: "ground", effect: "Nhốt đối thủ trong hố cát lún từ 4-5 lượt." },
  { id: "TM177", name: "TM177 - Spite", moveName: "spite", type: "ghost", effect: "Giảm PP của chiêu thức cuối cùng đối thủ vừa sử dụng." },
  { id: "TM178", name: "TM178 - Gravity", moveName: "gravity", type: "psychic", effect: "Tăng trọng lực khiến mọi Pokémon hệ Bay bị rơi xuống đất." },
  { id: "TM179", name: "TM179 - Smack Down", moveName: "smack-down", type: "rock", effect: "Ném đá kéo Pokémon đang bay xuống mặt đất." },
  { id: "TM180", name: "TM180 - Gyro Ball", moveName: "gyro-ball", type: "steel", effect: "Người dùng càng chậm hơn đối thủ sát thương càng mạnh." },
  { id: "TM181", name: "TM181 - Knock Off", moveName: "knock-off", type: "dark", effect: "Đánh rơi vật phẩm của đối thủ và gây thêm sát thương." },
  { id: "TM182", name: "TM182 - Bug Bite", moveName: "bug-bite", type: "bug", effect: "Cắn đối thủ và cướp luôn hiệu ứng quả Berry chúng đang cầm." },
  { id: "TM183", name: "TM183 - Super Fang", moveName: "super-fang", type: "normal", effect: "Gặm nhấm khiến đối thủ mất đúng một nửa HP hiện tại." },
  { id: "TM184", name: "TM184 - Vacuum Wave", moveName: "vacuum-wave", type: "fighting", effect: "Tạo sóng chân không tấn công ưu tiên (priority)." },
  { id: "TM185", name: "TM185 - Lunge", moveName: "lunge", type: "bug", effect: "Lao tới tấn công và giảm Attack của đối phương." },
  { id: "TM186", name: "TM186 - High Horsepower", moveName: "high-horsepower", type: "ground", effect: "Dùng toàn lực cơ thể húc mạnh vào đối thủ." },
  { id: "TM187", name: "TM187 - Icicle Spear", moveName: "icicle-spear", type: "ice", effect: "Phóng các mũi thương băng 2-5 lần liên tiếp." },
  { id: "TM188", name: "TM188 - Scald", moveName: "scald", type: "water", effect: "Bắn nước sôi, có 30% cơ hội gây bỏng đối phương." },
  { id: "TM189", name: "TM189 - Heat Crash", moveName: "heat-crash", type: "fire", effect: "Càng nặng hơn đối thủ sát thương gây ra càng lớn." },
  { id: "TM190", name: "TM190 - Solar Blade", moveName: "solar-blade", type: "grass", effect: "Tích tụ năng lượng mặt trời rồi chém mạnh ở lượt sau." },
  { id: "TM191", name: "TM191 - Uproar", moveName: "uproar", type: "normal", effect: "Hét lớn trong 3 lượt và ngăn tất cả Pokémon đi ngủ." },
  { id: "TM192", name: "TM192 - Focus Punch", moveName: "focus-punch", type: "fighting", effect: "Cú đấm cực mạnh nhưng dễ bị ngắt nếu bị tấn công trước." },
  { id: "TM193", name: "TM193 - Weather Ball", moveName: "weather-ball", type: "normal", effect: "Thay đổi hệ và sức mạnh tùy theo thời tiết hiện tại." },
  { id: "TM194", name: "TM194 - Grassy Glide", moveName: "grassy-glide", type: "grass", effect: "Đòn đánh ưu tiên nếu đang ở trong Địa hình Cỏ." },
  { id: "TM195", name: "TM195 - Burning Jealousy", moveName: "burning-jealousy", type: "fire", effect: "Gây bỏng đối thủ nếu chúng vừa được tăng chỉ số lượt đó." },
  { id: "TM196", name: "TM196 - Flip Turn", moveName: "flip-turn", type: "water", effect: "Tấn công rồi ngay lập tức rút về để đổi Pokémon." },
  { id: "TM197", name: "TM197 - Dual Wingbeat", moveName: "dual-wingbeat", type: "flying", effect: "Đập cánh tấn công đối thủ 2 lần liên tiếp." },
  { id: "TM198", name: "TM198 - Poltergeist", moveName: "poltergeist", type: "ghost", effect: "Điều khiển vật phẩm của đối thủ để tấn công chính chúng." },
  { id: "TM199", name: "TM199 - Lash Out", moveName: "lash-out", type: "dark", effect: "Sát thương gấp đôi nếu chỉ số bị giảm trong lượt đó." },
  { id: "TM200", name: "TM200 - Scale Shot", moveName: "scale-shot", type: "dragon", effect: "Bắn vảy 2-5 lần, tăng Speed nhưng giảm Defense." },
  { id: "TM201", name: "TM201 - Misty Explosion", moveName: "misty-explosion", type: "fairy", effect: "Phát nổ gây sát thương cực lớn, mạnh hơn trong Địa hình Sương mù." },

  // DLC 2: THE INDIGO DISK (TM202 - TM229)
  { id: "TM202", name: "TM202 - Pain Split", moveName: "pain-split", type: "normal", effect: "Chia đều tổng lượng HP hiện tại của người dùng và đối thủ." },
  { id: "TM203", name: "TM203 - Psych Up", moveName: "psych-up", type: "normal", effect: "Sao chép mọi thay đổi chỉ số hiện tại của mục tiêu." },
  { id: "TM204", name: "TM204 - Double-Edge", moveName: "double-edge", type: "normal", effect: "Cú húc liều mạng gây sát thương lớn nhưng bị phản đòn." },
  { id: "TM205", name: "TM205 - Endeavor", moveName: "endeavor", type: "normal", effect: "Làm HP đối thủ bằng đúng HP hiện tại của người dùng." },
  { id: "TM206", name: "TM206 - Petal Blizzard", moveName: "petal-blizzard", type: "grass", effect: "Tạo bão cánh hoa tấn công mọi Pokémon xung quanh." },
  { id: "TM207", name: "TM207 - Temper Flare", moveName: "temper-flare", type: "fire", effect: "Sát thương gấp đôi nếu chiêu trước đó bị trượt." },
  { id: "TM208", name: "TM208 - Whirlpool", moveName: "whirlpool", type: "water", effect: "Nhốt đối thủ trong vòng xoáy nước từ 4-5 lượt." },
  { id: "TM209", name: "TM209 - Muddy Water", moveName: "muddy-water", type: "water", effect: "Phun nước bùn, có thể giảm độ chính xác của đối thủ." },
  { id: "TM210", name: "TM210 - Superpower", moveName: "superpower", type: "fighting", effect: "Tấn công cực mạnh nhưng giảm Attack và Defense bản thân." },
  { id: "TM211", name: "TM211 - Electroweb", moveName: "electroweb", type: "electric", effect: "Giăng lưới điện gây sát thương và giảm Speed đối thủ." },
  { id: "TM212", name: "TM212 - Upper Hand", moveName: "upper-hand", type: "fighting", effect: "Đánh phủ đầu đòn ưu tiên và gây choáng đối thủ." },
  { id: "TM213", name: "TM213 - Coaching", moveName: "coaching", type: "fighting", effect: "Huấn luyện đồng đội để tăng Attack và Defense cho họ." },
  { id: "TM214", name: "TM214 - Sludge Wave", moveName: "sludge-wave", type: "poison", effect: "Sóng bùn độc tấn công tất cả Pokémon xung quanh." },
  { id: "TM215", name: "TM215 - Scorching Sands", moveName: "scorching-sands", type: "ground", effect: "Bắn cát nóng, có 30% cơ hội gây bỏng đối phương." },
  { id: "TM216", name: "TM216 - Feather Dance", moveName: "feather-dance", type: "flying", effect: "Nhảy múa tung lông vũ làm giảm mạnh Attack đối thủ." },
  { id: "TM217", name: "TM217 - Future Sight", moveName: "future-sight", type: "psychic", effect: "Gửi đòn tấn công tâm linh đến tương lai (2 lượt sau)." },
  { id: "TM218", name: "TM218 - Expanding Force", moveName: "expanding-force", type: "psychic", effect: "Mạnh hơn và tấn công mọi đối thủ trong Địa hình Tâm linh." },
  { id: "TM219", name: "TM219 - Skitter Smack", moveName: "skitter-smack", type: "bug", effect: "Tấn công áp sát và làm giảm Sp. Atk của đối thủ." },
  { id: "TM220", name: "TM220 - Meteor Beam", moveName: "meteor-beam", type: "rock", effect: "Tăng Sp. Atk ở lượt đầu và bắn tia thiên thạch ở lượt sau." },
  { id: "TM221", name: "TM221 - Throat Chop", moveName: "throat-chop", type: "dark", effect: "Chặt vào cổ họng ngăn đối thủ dùng chiêu âm thanh trong 2 lượt." },
  { id: "TM222", name: "TM222 - Breaking Swipe", moveName: "breaking-swipe", type: "dragon", effect: "Quất đuôi tấn công mọi đối thủ và giảm Attack của chúng." },
  { id: "TM223", name: "TM223 - Metal Sound", moveName: "metal-sound", type: "steel", effect: "Phát âm thanh kim loại chói tai làm giảm mạnh Sp. Def đối thủ." },
  { id: "TM224", name: "TM224 - Curse", moveName: "curse", type: "ghost", effect: "Hệ Ghost mất HP để nguyền rủa, hệ khác tăng Att/Def giảm Speed." },
  { id: "TM225", name: "TM225 - Hard Press", moveName: "hard-press", type: "steel", effect: "HP đối thủ càng nhiều, sát thương gây ra càng lớn." },
  { id: "TM226", name: "TM226 - Dragon Cheer", moveName: "dragon-cheer", type: "dragon", effect: "Cổ vũ đồng đội tăng tỉ lệ chí mạng (hiệu quả cao với hệ Rồng)." },
  { id: "TM227", name: "TM227 - Alluring Voice", moveName: "alluring-voice", type: "fairy", effect: "Gây rối loạn đối thủ nếu chúng vừa tăng chỉ số trong lượt đó." },
  { id: "TM228", name: "TM228 - Psychic Noise", moveName: "psychic-noise", type: "psychic", effect: "Gây sát thương âm thanh ngăn đối thủ hồi HP trong 2 lượt." },
  { id: "TM229", name: "TM229 - Tera Starstorm", moveName: "tera-starstorm", type: "stellar", effect: "Đòn đánh đặc trưng của Terapagos, gây sát thương hệ Stellar cực mạnh." },
];